name = "NoBannerNemo"
uuid = "cb2c744d-d98a-48ce-9f41-98711bc79bf6"
authors = ["Stefan Krastanov <stefan@krastanov.org>"]
version = "0.1.0"

[deps]
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"

[compat]
Nemo = "0.22"